/* GENERATED by tests/gen-video-reject.py -- do not edit.
 *
 * Rejection of video enum and flag values arriving in ordinary fields.
 * Regenerate after changing the carrying-site manifest; the enforcement
 * gate compares this file against that manifest.
 */

#ifndef VKR_VIDEO_REJECT_H
#define VKR_VIDEO_REJECT_H

#include <stdbool.h>

#include "vkr_common.h"

static inline bool
vkr_video_value_VkAccessFlags2(VkAccessFlags2 value)
{
   const VkAccessFlags2 video =
      (VkAccessFlags2)VK_ACCESS_2_VIDEO_DECODE_READ_BIT_KHR |
      (VkAccessFlags2)VK_ACCESS_2_VIDEO_DECODE_WRITE_BIT_KHR;
   return (value & video) != 0;
}

static inline bool
vkr_video_value_VkBufferUsageFlags(VkBufferUsageFlags value)
{
   const VkBufferUsageFlags video =
      (VkBufferUsageFlags)VK_BUFFER_USAGE_VIDEO_DECODE_DST_BIT_KHR |
      (VkBufferUsageFlags)VK_BUFFER_USAGE_VIDEO_DECODE_SRC_BIT_KHR;
   return (value & video) != 0;
}

static inline bool
vkr_video_value_VkBufferUsageFlags2(VkBufferUsageFlags2 value)
{
   const VkBufferUsageFlags2 video =
      (VkBufferUsageFlags2)VK_BUFFER_USAGE_2_VIDEO_DECODE_DST_BIT_KHR |
      (VkBufferUsageFlags2)VK_BUFFER_USAGE_2_VIDEO_DECODE_SRC_BIT_KHR |
      (VkBufferUsageFlags2)VK_BUFFER_USAGE_2_VIDEO_ENCODE_DST_BIT_KHR |
      (VkBufferUsageFlags2)VK_BUFFER_USAGE_2_VIDEO_ENCODE_SRC_BIT_KHR;
   return (value & video) != 0;
}

static inline bool
vkr_video_value_VkImageLayout(VkImageLayout value)
{
   switch (value) {
   case VK_IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR:
   case VK_IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR:
   case VK_IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR:
      return true;
   default:
      return false;
   }
}

static inline bool
vkr_video_value_VkImageUsageFlags(VkImageUsageFlags value)
{
   const VkImageUsageFlags video =
      (VkImageUsageFlags)VK_IMAGE_USAGE_VIDEO_DECODE_DPB_BIT_KHR |
      (VkImageUsageFlags)VK_IMAGE_USAGE_VIDEO_DECODE_DST_BIT_KHR |
      (VkImageUsageFlags)VK_IMAGE_USAGE_VIDEO_DECODE_SRC_BIT_KHR;
   return (value & video) != 0;
}

static inline bool
vkr_video_value_VkObjectType(VkObjectType value)
{
   switch (value) {
   case VK_OBJECT_TYPE_VIDEO_SESSION_KHR:
   case VK_OBJECT_TYPE_VIDEO_SESSION_PARAMETERS_KHR:
      return true;
   default:
      return false;
   }
}

static inline bool
vkr_video_value_VkPipelineStageFlags2(VkPipelineStageFlags2 value)
{
   const VkPipelineStageFlags2 video =
      (VkPipelineStageFlags2)VK_PIPELINE_STAGE_2_VIDEO_DECODE_BIT_KHR;
   return (value & video) != 0;
}

static inline bool
vkr_video_value_VkQueryResultFlags(VkQueryResultFlags value)
{
   const VkQueryResultFlags video =
      (VkQueryResultFlags)VK_QUERY_RESULT_WITH_STATUS_BIT_KHR;
   return (value & video) != 0;
}

static inline bool
vkr_video_value_VkQueryType(VkQueryType value)
{
   switch (value) {
   case VK_QUERY_TYPE_RESULT_STATUS_ONLY_KHR:
      return true;
   default:
      return false;
   }
}

static inline bool
vkr_video_reject_VkAttachmentDescription(const VkAttachmentDescription *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->finalLayout))
      return true;
   if (vkr_video_value_VkImageLayout(s->initialLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkAttachmentDescription2(const VkAttachmentDescription2 *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->finalLayout))
      return true;
   if (vkr_video_value_VkImageLayout(s->initialLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkAttachmentDescriptionStencilLayout(const VkAttachmentDescriptionStencilLayout *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->stencilFinalLayout))
      return true;
   if (vkr_video_value_VkImageLayout(s->stencilInitialLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkAttachmentReference(const VkAttachmentReference *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->layout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkAttachmentReference2(const VkAttachmentReference2 *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->layout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkAttachmentReferenceStencilLayout(const VkAttachmentReferenceStencilLayout *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->stencilLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkBlitImageInfo2(const VkBlitImageInfo2 *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->dstImageLayout))
      return true;
   if (vkr_video_value_VkImageLayout(s->srcImageLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkBufferCreateInfo(const VkBufferCreateInfo *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkBufferUsageFlags(s->usage))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkBufferMemoryBarrier2(const VkBufferMemoryBarrier2 *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkAccessFlags2(s->dstAccessMask))
      return true;
   if (vkr_video_value_VkPipelineStageFlags2(s->dstStageMask))
      return true;
   if (vkr_video_value_VkAccessFlags2(s->srcAccessMask))
      return true;
   if (vkr_video_value_VkPipelineStageFlags2(s->srcStageMask))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkBufferUsageFlags2CreateInfo(const VkBufferUsageFlags2CreateInfo *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkBufferUsageFlags2(s->usage))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkCopyBufferToImageInfo2(const VkCopyBufferToImageInfo2 *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->dstImageLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkCopyImageInfo2(const VkCopyImageInfo2 *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->dstImageLayout))
      return true;
   if (vkr_video_value_VkImageLayout(s->srcImageLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkCopyImageToBufferInfo2(const VkCopyImageToBufferInfo2 *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->srcImageLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkCopyImageToImageInfo(const VkCopyImageToImageInfo *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->dstImageLayout))
      return true;
   if (vkr_video_value_VkImageLayout(s->srcImageLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkDescriptorImageInfo(const VkDescriptorImageInfo *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->imageLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkFramebufferAttachmentImageInfo(const VkFramebufferAttachmentImageInfo *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageUsageFlags(s->usage))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkHostImageLayoutTransitionInfo(const VkHostImageLayoutTransitionInfo *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->newLayout))
      return true;
   if (vkr_video_value_VkImageLayout(s->oldLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkImageCreateInfo(const VkImageCreateInfo *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->initialLayout))
      return true;
   if (vkr_video_value_VkImageUsageFlags(s->usage))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkImageDescriptorInfoEXT(const VkImageDescriptorInfoEXT *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->layout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkImageMemoryBarrier(const VkImageMemoryBarrier *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->newLayout))
      return true;
   if (vkr_video_value_VkImageLayout(s->oldLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkImageMemoryBarrier2(const VkImageMemoryBarrier2 *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkAccessFlags2(s->dstAccessMask))
      return true;
   if (vkr_video_value_VkPipelineStageFlags2(s->dstStageMask))
      return true;
   if (vkr_video_value_VkImageLayout(s->newLayout))
      return true;
   if (vkr_video_value_VkImageLayout(s->oldLayout))
      return true;
   if (vkr_video_value_VkAccessFlags2(s->srcAccessMask))
      return true;
   if (vkr_video_value_VkPipelineStageFlags2(s->srcStageMask))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkImageStencilUsageCreateInfo(const VkImageStencilUsageCreateInfo *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageUsageFlags(s->stencilUsage))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkImageViewUsageCreateInfo(const VkImageViewUsageCreateInfo *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageUsageFlags(s->usage))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkMemoryBarrier2(const VkMemoryBarrier2 *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkAccessFlags2(s->dstAccessMask))
      return true;
   if (vkr_video_value_VkPipelineStageFlags2(s->dstStageMask))
      return true;
   if (vkr_video_value_VkAccessFlags2(s->srcAccessMask))
      return true;
   if (vkr_video_value_VkPipelineStageFlags2(s->srcStageMask))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkPhysicalDeviceExternalBufferInfo(const VkPhysicalDeviceExternalBufferInfo *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkBufferUsageFlags(s->usage))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkPhysicalDeviceImageFormatInfo2(const VkPhysicalDeviceImageFormatInfo2 *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageUsageFlags(s->usage))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkPhysicalDeviceSparseImageFormatInfo2(const VkPhysicalDeviceSparseImageFormatInfo2 *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageUsageFlags(s->usage))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkQueryPoolCreateInfo(const VkQueryPoolCreateInfo *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkQueryType(s->queryType))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkRenderingAttachmentInfo(const VkRenderingAttachmentInfo *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->imageLayout))
      return true;
   if (vkr_video_value_VkImageLayout(s->resolveImageLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkRenderingFragmentShadingRateAttachmentInfoKHR(const VkRenderingFragmentShadingRateAttachmentInfoKHR *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->imageLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkResolveImageInfo2(const VkResolveImageInfo2 *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkImageLayout(s->dstImageLayout))
      return true;
   if (vkr_video_value_VkImageLayout(s->srcImageLayout))
      return true;
   return false;
}

static inline bool
vkr_video_reject_VkSemaphoreSubmitInfo(const VkSemaphoreSubmitInfo *s)
{
   if (!s)
      return false;
   if (vkr_video_value_VkPipelineStageFlags2(s->stageMask))
      return true;
   return false;
}

static inline bool
vkr_video_reject_present_VkVideoDecodeH264ProfileInfoKHR(const VkVideoDecodeH264ProfileInfoKHR *s)
{
   /* Presence is the violation; no member is legitimate here. */
   return s != NULL;
}

static inline bool
vkr_video_reject_present_VkVideoDecodeUsageInfoKHR(const VkVideoDecodeUsageInfoKHR *s)
{
   /* Presence is the violation; no member is legitimate here. */
   return s != NULL;
}

static inline bool
vkr_video_reject_present_VkVideoProfileInfoKHR(const VkVideoProfileInfoKHR *s)
{
   /* Presence is the violation; no member is legitimate here. */
   return s != NULL;
}

static inline bool
vkr_video_reject_present_VkVideoProfileListInfoKHR(const VkVideoProfileListInfoKHR *s)
{
   /* Presence is the violation; no member is legitimate here. */
   return s != NULL;
}

/* Walk a pNext chain and reject any chained struct that carries a
 * video value. A chained struct is never reached by validating the
 * struct it hangs off: the guest attaches it to an ordinary create
 * info and the values ride in from the side.
 */
static inline bool
vkr_video_reject_pnext(const void *pnext)
{
   for (const VkBaseInStructure *s = pnext; s; s = s->pNext) {
      switch (s->sType) {
      /* VkVideoDecodeH264ProfileInfoKHR: presence alone is the violation. */
      case VK_STRUCTURE_TYPE_VIDEO_DECODE_H264_PROFILE_INFO_KHR:
         return vkr_video_reject_present_VkVideoDecodeH264ProfileInfoKHR((const VkVideoDecodeH264ProfileInfoKHR *)s);
      /* VkVideoDecodeUsageInfoKHR: presence alone is the violation. */
      case VK_STRUCTURE_TYPE_VIDEO_DECODE_USAGE_INFO_KHR:
         return vkr_video_reject_present_VkVideoDecodeUsageInfoKHR((const VkVideoDecodeUsageInfoKHR *)s);
      /* VkVideoProfileInfoKHR: presence alone is the violation. */
      case VK_STRUCTURE_TYPE_VIDEO_PROFILE_INFO_KHR:
         return vkr_video_reject_present_VkVideoProfileInfoKHR((const VkVideoProfileInfoKHR *)s);
      /* VkVideoProfileListInfoKHR: presence alone is the violation. */
      case VK_STRUCTURE_TYPE_VIDEO_PROFILE_LIST_INFO_KHR:
         return vkr_video_reject_present_VkVideoProfileListInfoKHR((const VkVideoProfileListInfoKHR *)s);
      case VK_STRUCTURE_TYPE_ATTACHMENT_DESCRIPTION_STENCIL_LAYOUT:
         if (vkr_video_reject_VkAttachmentDescriptionStencilLayout((const VkAttachmentDescriptionStencilLayout *)s))
            return true;
         break;
      case VK_STRUCTURE_TYPE_ATTACHMENT_REFERENCE_STENCIL_LAYOUT:
         if (vkr_video_reject_VkAttachmentReferenceStencilLayout((const VkAttachmentReferenceStencilLayout *)s))
            return true;
         break;
      case VK_STRUCTURE_TYPE_BUFFER_USAGE_FLAGS_2_CREATE_INFO:
         if (vkr_video_reject_VkBufferUsageFlags2CreateInfo((const VkBufferUsageFlags2CreateInfo *)s))
            return true;
         break;
      case VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO:
         if (vkr_video_reject_VkImageStencilUsageCreateInfo((const VkImageStencilUsageCreateInfo *)s))
            return true;
         break;
      case VK_STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO:
         if (vkr_video_reject_VkImageViewUsageCreateInfo((const VkImageViewUsageCreateInfo *)s))
            return true;
         break;
      case VK_STRUCTURE_TYPE_MEMORY_BARRIER_2:
         if (vkr_video_reject_VkMemoryBarrier2((const VkMemoryBarrier2 *)s))
            return true;
         break;
      case VK_STRUCTURE_TYPE_RENDERING_FRAGMENT_SHADING_RATE_ATTACHMENT_INFO_KHR:
         if (vkr_video_reject_VkRenderingFragmentShadingRateAttachmentInfoKHR((const VkRenderingFragmentShadingRateAttachmentInfoKHR *)s))
            return true;
         break;
      default:
         break;
      }
   }
   return false;
}

#endif /* VKR_VIDEO_REJECT_H */
